#Wed Mar 12 15:11:47 UTC 2025
micronaut:
  application:
    name=restcountries
  router.static-resources.default:
    enabled: true
    paths: classpath:static
    mapping: "/**"
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedMethods:
            - GET
  caches:
    rate-limiter:
      expire-after-access: 10m